version: "2"
run:
  tests: true
  timeout: 5m
output:
  formats:
    text:
      print-issued-lines: false
      colors: true
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - dogsled
    - dupl
    - dupword
    - err113
    - errchkjson
    - exhaustruct
    - exptostd
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - goprintffuncname
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - musttag
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - recvcheck
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wastedassign
    - whitespace
    - wsl
    - wrapcheck
    - funcorder
    - maintidx
    - forcetypeassert
    - errcheck
    - errorlint

  settings:
    wrapcheck:
      ignore-sigs:
        - errors.New
        - errors.Errorf
        - errors.Join
        - errors.Wrap
        - errors.Wrapf
        - errors.WithStack
        - errors.WithStack2
        - errors.WithStack3
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: use github.com/alecthomas/errors
            - pkg: github.com/stretchr/testify
              desc: use github.com/alecthomas/assert/v2
            - pkg: errors
              desc: use github.com/alecthomas/errors
            - pkg: braces.dev/errtrace
              desc: use github.com/alecthomas/errors
            - pkg: os/exec
              desc: use github.com/block/ftl/internal/exec
            - pkg: golang.design/x/reflect
              desc: use github.com/block/ftl/common/reflect
            - pkg: github.com/reugn/go-quartz/logger
              desc: use github.com/block/ftl/internal/log
    dupl:
      threshold: 100
    errcheck:
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 8
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - ifElseChain
    gocyclo:
      min-complexity: 20
    govet:
      enable:
        - shadow
    spancheck:
      extra-start-span-signatures:
        - github.com/block/ftl/backend/controller/observability.BeginSpan:opentelemetry
    # exhaustruct:
    #   include:
    #     - '^github.com/block/ftl/common/schema\.Module$'
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: "^(G104|G204):"
      - path: (.+)\.go$
        text: Error return value of .(.*\.Help|.*\.MarkFlagRequired|(os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*Print(f|ln|)|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: "internal error: no range for"
      - path: (.+)\.go$
        text: exported method `.*\.(MarshalJSON|UnmarshalJSON|URN|Payload|GoString|Close|Provides|Requires|ExcludeFromHash|MarshalText|UnmarshalText|Description|Check|Poll|Severity)` should have comment or be unexported
      - path: (.+)\.go$
        text: composite literal uses unkeyed fields
      - path: (.+)\.go$
        text: declaration of "err" shadows declaration
      - path: (.+)\.go$
        text: by other packages, and that stutters
      - path: (.+)\.go$
        text: Potential file inclusion via variable
      - path: (.+)\.go$
        text: at least one file in a package should have a package comment
      - path: (.+)\.go$
        text: bad syntax for struct tag pair
      - path: (.+)\.go$
        text: should have comment or be unexported
      - path: (.+)\.go$
        text: package-comments
      - path: (.+)\.go$
        text: parameter testing.TB should have name tb
      - path: (.+)\.go$
        text: blank-imports
      - path: (.+)\.go$
        text: should have comment \(or a comment on this block\) or be unexported
      - path: (.+)\.go$
        text: caseOrder
      - path: (.+)\.go$
        text: unused-parameter
      - path: (.+)\.go$
        text: "^loopclosure:"
      - path: (.+)\.go$
        text: 'shadow: declaration of "ctx" shadows declaration at'
      - path: (.+)\.go$
        text: 'shadow: declaration of "ok" shadows declaration'
      - path: (.+)\.go$
        text: "^dot-imports:"
      - path: (.+)\.go$
        text: fmt.Errorf can be replaced with errors.New
      - path: (.+)\.go$
        text: fmt.Sprintf can be replaced with string concatenation
      - path: (.+)\.go$
        text: strings.Title has been deprecated
      - path: (.+)\.go$
        text: error returned from external package is unwrapped.*TranslatePGError
      - path: (.+)\.go$
        text: struct literal uses unkeyed fields
      - path: (.+)\.go$
        text: "exported: comment on exported type"
      - path: (.+)\.go$
        text: result .* \(error\) is always nil
      - path: (.+)\.go$
        text: QF1001
    paths:
      - cmd/protopkg/main.go
      - resources
      - old
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
